# Generated by Django 2.0.1 on 2018-03-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pitchdeck',
            },
        ),
        migrations.AlterModelTable(
            name='login',
            table='signin',
        ),
    ]
