# Generated by Django 2.0.1 on 2018-03-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0002_auto_20180318_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startup',
            table='startup_name',
        ),
    ]
