# Generated by Django 2.0.1 on 2018-03-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0003_auto_20180318_0920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startup',
            table='startup',
        ),
    ]
