# Generated by Django 2.0.1 on 2018-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0004_auto_20180318_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='startup',
            table=None,
        ),
    ]
