# Generated by Django 2.0.1 on 2018-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0006_auto_20180320_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='null', max_length=8),
        ),
    ]
