# Generated by Django 2.0.1 on 2018-03-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0007_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
