# Generated by Django 2.0.1 on 2018-03-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0015_auto_20180330_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
