# Generated by Django 2.0.1 on 2018-03-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0016_auto_20180330_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, upload_to='pitchdeck/profile_images'),
        ),
    ]
