# Generated by Django 2.0.1 on 2018-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0017_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
