# Generated by Django 2.0.1 on 2018-03-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0021_auto_20180330_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=100)),
                ('var2', models.CharField(max_length=100)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch.userprofile')),
            ],
            options={
                'db_table': 'startup',
            },
        ),
    ]
