# Generated by Django 2.0.1 on 2018-03-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0022_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_name',
            name='uname',
        ),
    ]
