# Generated by Django 2.0.1 on 2018-03-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0023_remove_u_name_uname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='u_name',
            new_name='startup_data',
        ),
    ]
